from __future__ import annotations

import hashlib
import logging
import re
from typing import Any, Mapping

logger = logging.getLogger(__name__)


PULL_SOURCE_KIND = "pull"
ISSUE_SOURCE_KIND = "issue"
TEXT_SOURCE_KIND = "text"
NON_PR_SOURCE_KINDS = frozenset({ISSUE_SOURCE_KIND, TEXT_SOURCE_KIND})
_TITLE_PATTERN = re.compile(r"(?:^|\n)Title:\s*(.+)")


def normalize_source_kind(value: Any) -> str:
    normalized = (_safe_text(value) or "").lower()
    return normalized


def is_non_pr_source_kind(value: Any) -> bool:
    return normalize_source_kind(value) in NON_PR_SOURCE_KINDS


def is_issue_source_kind(value: Any) -> bool:
    return normalize_source_kind(value) == ISSUE_SOURCE_KIND


def is_text_source_kind(value: Any) -> bool:
    return normalize_source_kind(value) == TEXT_SOURCE_KIND


def build_manual_text_task_number(
    *, repo: str, text: str, title: str | None = None
) -> int:
    digest = hashlib.sha256(f"{repo}\n{title or ''}\n{text}".encode("utf-8")).digest()
    parsed = int.from_bytes(digest[:4], "big") & 0x7FFFFFFF
    if parsed == 0:
        logger.debug(
            "SHA256 hash collision detected for repo=%s, using fallback value 1", repo
        )
        return 1
    return parsed


def extract_task_title(normalized_review: Mapping[str, Any]) -> str | None:
    explicit_title = _safe_text(normalized_review.get("task_title"))
    if explicit_title:
        return explicit_title
    issue_title = _extract_title_from_items(normalized_review.get("must_fix"))
    if issue_title:
        return issue_title
    issue_number = coerce_positive_int(normalized_review.get("issue_number"))
    if issue_number is not None:
        return f"issue #{issue_number}"
    return None


def build_task_context_lines(
    *,
    repo: str,
    pr_number: int,
    head_sha: str,
    normalized_review: Mapping[str, Any],
) -> list[str]:
    source_kind = normalize_source_kind(normalized_review.get("source_kind"))
    if source_kind == ISSUE_SOURCE_KIND:
        lines = [
            "You are an autofix agent working on a manually submitted GitHub issue.",
            "",
            "Context:",
            f"- Repository: {repo}",
        ]
        issue_number = _safe_text(normalized_review.get("issue_number"))
        if issue_number:
            lines.append(f"- Issue: #{issue_number}")
        source_url = _safe_text(normalized_review.get("manual_issue_source_url"))
        if source_url:
            lines.append(f"- Source URL: {source_url}")
        lines.append(f"- Head SHA: {head_sha}")
        return lines
    if source_kind == TEXT_SOURCE_KIND:
        lines = [
            "You are an autofix agent working on a manually submitted software task.",
            "",
            "Context:",
            f"- Repository: {repo}",
        ]
        task_title = extract_task_title(normalized_review)
        if task_title:
            lines.append(f"- Task: {task_title}")
        lines.append("- Source: manual text input")
        lines.append(f"- Head SHA: {head_sha}")
        return lines
    return [
        "You are an autofix agent working on a pull request.",
        "",
        "Context:",
        f"- Repository: {repo}",
        f"- Pull Request: #{pr_number}",
        f"- Head SHA: {head_sha}",
    ]


def build_task_pull_request_title(normalized_review: Mapping[str, Any]) -> str:
    title = extract_task_title(normalized_review)
    if title:
        return f"fix: {title}"
    if is_text_source_kind(normalized_review.get("source_kind")):
        return "fix: resolve manual task"
    return "fix: resolve manual issue"


def build_task_pull_request_body(normalized_review: Mapping[str, Any]) -> str:
    source_kind = normalize_source_kind(normalized_review.get("source_kind"))
    issue_number = coerce_positive_int(normalized_review.get("issue_number"))
    source_url = _safe_text(normalized_review.get("manual_issue_source_url")) or ""
    title = extract_task_title(normalized_review)
    lines = [
        "## Summary",
        "- Automated fix generated by software-factory.",
    ]
    if source_kind == ISSUE_SOURCE_KIND and issue_number is not None:
        issue_line = f"- Resolves issue #{issue_number}"
        if title:
            issue_line = f"{issue_line}: {title}"
        lines.append(issue_line)
    elif title:
        lines.append(f"- Resolves manual task: {title}")
    else:
        lines.append("- Resolves a manually submitted task.")
    if source_url:
        lines.append(f"- Source: {source_url}")
    preview = _first_non_empty_line(
        _safe_text(normalized_review.get("task_text")) or ""
    )
    if preview and preview != title:
        lines.append(f"- Context: {preview[:180]}")
    if source_kind == ISSUE_SOURCE_KIND and issue_number is not None:
        lines.extend(["", f"Closes #{issue_number}"])
    return "\n".join(lines)


def coerce_positive_int(value: Any) -> int | None:
    if isinstance(value, bool) or value is None:
        return None
    try:
        parsed = int(str(value).strip())
    except (TypeError, ValueError):
        return None
    return parsed if parsed > 0 else None


def _extract_title_from_items(value: Any) -> str | None:
    if not isinstance(value, list):
        return None
    for item in value:
        if not isinstance(item, Mapping):
            continue
        text = _safe_text(item.get("text")) or ""
        match = _TITLE_PATTERN.search(text)
        if match is None:
            continue
        title = match.group(1).strip()
        if title:
            return title
    return None


def _first_non_empty_line(text: str) -> str | None:
    for line in text.splitlines():
        normalized = line.strip()
        if normalized:
            return normalized
    return None


def _safe_text(value: Any) -> str | None:
    if value is None:
        return None
    normalized = str(value).strip()
    return normalized or None
