"""Provider interfaces and registry utilities."""

from app.providers.registry import (
    FORGE_PROVIDER_CATEGORY,
    GIT_REMOTE_PROVIDER_CATEGORY,
    TASK_SOURCE_PROVIDER_CATEGORY,
    WEBHOOK_PROVIDER_CATEGORY,
    ProviderRegistryError,
    ProviderLookupError,
    ProviderRegistrationError,
    RegistrySnapshot,
    get_forge_provider,
    get_git_remote_provider,
    get_task_source_provider,
    get_webhook_provider,
    initialize_provider_registry,
    list_registered_provider_names,
    register_forge_provider,
    register_git_remote_provider,
    register_task_source_provider,
    register_webhook_provider,
    reset_provider_registry,
    resolve_provider_name,
    snapshot_registry,
)
from app.providers.types import (
    DEFAULT_PROVIDER_NAME,
    ForgeProvider,
    GitRemoteProvider,
    PullRequestMetadata,
    PullRequestUpsertResult,
    TaskSourceProvider,
    WebhookProvider,
)

__all__ = [
    "DEFAULT_PROVIDER_NAME",
    "FORGE_PROVIDER_CATEGORY",
    "TASK_SOURCE_PROVIDER_CATEGORY",
    "WEBHOOK_PROVIDER_CATEGORY",
    "GIT_REMOTE_PROVIDER_CATEGORY",
    "ProviderRegistryError",
    "ProviderLookupError",
    "ProviderRegistrationError",
    "RegistrySnapshot",
    "ForgeProvider",
    "TaskSourceProvider",
    "WebhookProvider",
    "GitRemoteProvider",
    "PullRequestUpsertResult",
    "PullRequestMetadata",
    "resolve_provider_name",
    "register_forge_provider",
    "register_task_source_provider",
    "register_webhook_provider",
    "register_git_remote_provider",
    "get_forge_provider",
    "get_task_source_provider",
    "get_webhook_provider",
    "get_git_remote_provider",
    "initialize_provider_registry",
    "list_registered_provider_names",
    "snapshot_registry",
    "reset_provider_registry",
]
