name: Linked Issue Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review, labeled, unlabeled]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  linked-issue:
    name: Require Linked Issue
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: nearform-actions/github-action-check-linked-issues@05f1d702b9a2d51123a6f32a51292eff6dc78815 # v1.8.3
        id: check-linked-issues
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          exclude-branches: "dependabot/**"
          exclude-labels: "skip-issue-check, documentation"
          loose-matching: true
          comment: false
